import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import UiProvider from "@/lib/UiProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-main-bg`}>
        <UiProvider>
          {children}
          <div id="popup"></div>
          <Toaster position="bottom-right" />
        </UiProvider>
      </body>
    </html>
  );
}